% =================================
% =          ACG grammar          =
% =================================

% This grammar contains some examples from the following articles.
%
% Makoto Kanazawa (2015) Syntactic Features for Regular Constraints and an Approximation of Directional
% Slashes in Abstract Categorial Grammars, in Yusuke Kubota and Robert Levine (eds) Proceedings of
% Empirical Advances in Categorial Grammars, pp. 34-70.
%
% This grammar adds ditransitive verbs to acg_grammar.pl, and this rather complicates the system
% (more realistic grammars in the style of CCGbank and TLGbank require at least two arguments to the
% left and two arguments to the right).

% define operators to allow for easier specification of
% hybrid type-logical grammar lexical entries.
%
% WARNING: in case of doubt, use parentheses to disambiguate!
% I have deliberately not changed the definitions of standard
% mathematical and logical operations of Prolog, notably |
% (alternative of ; for use in DCG), ^, /, * and +.
%
% This means for example that:
% c/d*b/c = ((c/d)*b)/c
% which corresponds to a left-to-right evaluation of the
% mathematical functions of division and multiplication.
%
% It also means that (s|s|np) = (s|(s|np))
%
% However, we do have the familiar a/b/c = (a/b)/c and
% c\b\a = (c\(b\a) and even a\b/c = (a\b)/c.
%
% For lambda terms, X^M is short for lambda(X,M) and M@N
% is short for appl(M,N). As expected, X^Y^Z^X@Y@Z is
% short for lambda(X,lambda(Y,lambda(Z,appl(appl(X,Y),Z))))
% though be warned that X@Y+V@Z corresponds to (X@Y)+(V@Z)

:- op(400, xfy, \).
:- op(190, yfx, @).

:- abolish(lex/3), abolish(lex/4), abolish(test/1), abolish(atomic_formula/3), abolish(atomic_formula/1), abolish(macro/2).

macro(tv_i, ((s(L,R)|np(L,0))|np(0,R))). 

atomic_formula(n(_,_)).
atomic_formula(np(_,_)).
atomic_formula(s(_,_)).
atomic_formula(s1(_,_)).

lex(captain_jack, np(0,0), captain_jack, captain_jack).
lex(lobster, np(0,0), lobster, lobster).
lex(bananafish, np(0,0), bananafish, bananafish).

lex(served, (np(0, 0)->np(0, 0)->s(0, 0)), lambda(A, lambda(B, B+ (served+A))), serve).
lex(served, (np(0, 0)->np(1, 0)->s(1, 0)), lambda(A, lambda(B, B+ (served+A))), serve).
lex(served, (np(0, 0)->np(21, 0)->s(21, 0)), lambda(A, lambda(B, B+ (served+A))), serve).
lex(served, (np(0, 1)->np(0, 0)->s(0, 1)), lambda(A, lambda(B, B+ (served+A))), serve).
lex(served, (np(0, 1)->np(1, 0)->s(1, 1)), lambda(A, lambda(B, B+ (served+A))), serve).
lex(served, (np(0, 1)->np(21, 0)->s(21, 1)), lambda(A, lambda(B, B+ (served+A))), serve).
lex(served, (np(0, 12)->np(0, 0)->s(0, 12)), lambda(A, lambda(B, B+ (served+A))), serve).
lex(served, (np(0, 12)->np(1, 0)->s(1, 12)), lambda(A, lambda(B, B+ (served+A))), serve).
lex(served, (np(0, 12)->np(21, 0)->s(21, 12)), lambda(A, lambda(B, B+ (served+A))), serve).

% lambda(A,lambda(B,B+ (appl(O_L(1),appl(A,epsilon(L,1)))+today)))
lex(today, ((np(1, 0)->s(1, 0))->np(0, 0)->s(0, 0)), lambda(A, lambda(B, B+ (appl(A, epsilon)+today))), today).
lex(today, ((np(1, 0)->s(1, 0))->np(1, 0)->s(1, 0)), lambda(A, lambda(B, B+ (appl(A, epsilon)+today))), today).
lex(today, ((np(1, 0)->s(1, 0))->np(21, 0)->s(21, 0)), lambda(A, lambda(B, B+ (appl(A, epsilon)+today))), today).

% lambda(A,lambda(B,B+ (appl(O_L(1),appl(A,epsilon(L,1)))+yesterday)))
lex(yesterday, ((np(1, 0)->s(1, 0))->np(0, 0)->s(0, 0)), lambda(A, lambda(B, B+ (appl(A, epsilon)+yesterday))), yesterday).
lex(yesterday, ((np(1, 0)->s(1, 0))->np(1, 0)->s(1, 0)), lambda(A, lambda(B, B+ (appl(A, epsilon)+yesterday))), yesterday).
lex(yesterday, ((np(1, 0)->s(1, 0))->np(21, 0)->s(21, 0)), lambda(A, lambda(B, B+ (appl(A, epsilon)+yesterday))), yesterday).

% lambda(A,lambda(B,B+ (appl(O_L(1),appl(A,epsilon(L,1)))+discreetly)))
lex(discreetly, ((np(1, 0)->s(1, 0))->np(0, 0)->s(0, 0)), lambda(A, lambda(B, B+ (appl(A, epsilon)+discreetly))), discreetly).
lex(discreetly, ((np(1, 0)->s(1, 0))->np(1, 0)->s(1, 0)), lambda(A, lambda(B, B+ (appl(A, epsilon)+discreetly))), discreetly).
lex(discreetly, ((np(1, 0)->s(1, 0))->np(21, 0)->s(21, 0)), lambda(A, lambda(B, B+ (appl(A, epsilon)+discreetly))), discreetly).


% coordination: (X\X)/X, with X = ((np\s)/np)\(np\s), 81 entries
% (((np\s)/np)\(np\s))\(((np\s)/np)\(np\s)))/(((np\s)/np)\(np\s))
% lambda(A,lambda(B,lambda(C,lambda(D,D+ (appl(O_R(1),appl(O_L(1),appl(appl(C,epsilon(R,1)),epsilon(L,1))))+ (appl(O_L(1),appl(O_L(2),appl(appl(B,lambda(E,lambda(F,F+ (epsilon(L,1)+E)))),epsilon(L,2))))+ (and+appl(O_L(1),appl(O_L(2),appl(appl(A,lambda(G,lambda(H,H+ (epsilon(L,1)+G)))),epsilon(L,2)))))))))))
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 1))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 1))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 1))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 12))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 12))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 12))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 1))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 1))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 1))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 12))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 12))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 12))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 1))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 1))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 1))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 12))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 12))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 12))-> ((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 1))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 1))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 1))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 12))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 12))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 12))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 1))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 1))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 1))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 12))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 12))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 12))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 1))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 1))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 1))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 12))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 12))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 12))-> ((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 1))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 1))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 1))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 12))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 12))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 12))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 1))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 1))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 1))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 12))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 12))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 12))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 0)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 1))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 1))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 1))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 1)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 12))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 12))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).
lex(and, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 12))-> ((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))-> (np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 12)), lambda(A, lambda(B, lambda(C, lambda(D, D+ (appl(appl(C, epsilon), epsilon)+ (appl(appl(B, lambda(E, lambda(F, F+E))), epsilon)+ (and+appl(appl(A, lambda(G, lambda(H, H+G))), epsilon)))))))), lambda(P,lambda(Q,lambda(R,lambda(X,bool(appl(appl(Q,R),X),&,appl(appl(P,R),X))))))).

% lambda(A,appl(O_L(1),appl(O_L(2),appl(appl(A,lambda(B,lambda(C,C+ (epsilon(L,1)+B)))),epsilon(L,2))))+end)
lex(end, (((np(0, 0)->np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))->s(0, 0)), lambda(A, appl(appl(A, lambda(B, lambda(C, C+B))), epsilon)+end), end).
lex(end, (((np(0, 1)->np(2, 0)->s(21, 1))->np(2, 0)->s(21, 0))->s(0, 0)), lambda(A, appl(appl(A, lambda(B, lambda(C, C+B))), epsilon)+end), end).
lex(end, (((np(0, 12)->np(2, 0)->s(21, 12))->np(2, 0)->s(21, 0))->s(0, 0)), lambda(A, appl(appl(A, lambda(B, lambda(C, C+B))), epsilon)+end), end).

% lambda(A,lambda(B,B+ (appl(O_R(1),appl(O_L(1),appl(appl(A,epsilon(R,1)),epsilon(L,1))))+end)))
%lex(end, ((np(0, 1)->np(1, 0)->s(1, 1))->np(0, 0)->s(0, 0)), lambda(A, lambda(B, B+ (appl(appl(A, epsilon), epsilon)+end))), end).
%lex(end, ((np(0, 1)->np(1, 0)->s(1, 1))->np(1, 0)->s(1, 0)), lambda(A, lambda(B, B+ (appl(appl(A, epsilon), epsilon)+end))), end).
%lex(end, ((np(0, 1)->np(1, 0)->s(1, 1))->np(21, 0)->s(21, 0)), lambda(A, lambda(B, B+ (appl(appl(A, epsilon), epsilon)+end))), end).


% lambda(A,lambda(B,lambda(C,C+ (appl(O_L(1),appl(B,epsilon(L,1)))+ (very+appl(O_L(1),appl(O_L(2),appl(appl(A,lambda(D,D+epsilon(L,1))),epsilon(L,2)))))))))

lex(very, (((np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(1, 0)->s(1, 0))->np(0, 0)->s(0, 0)), lambda(A, lambda(B, lambda(C, C+ (appl(B, epsilon)+ (very+appl(appl(A, lambda(D, D)), epsilon)))))), very).
lex(very, (((np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(1, 0)->s(1, 0))->np(1, 0)->s(1, 0)), lambda(A, lambda(B, lambda(C, C+ (appl(B, epsilon)+ (very+appl(appl(A, lambda(D, D)), epsilon)))))), very).
lex(very, (((np(2, 0)->s(21, 0))->np(2, 0)->s(21, 0))-> (np(1, 0)->s(1, 0))->np(21, 0)->s(21, 0)), lambda(A, lambda(B, lambda(C, C+ (appl(B, epsilon)+ (very+appl(appl(A, lambda(D, D)), epsilon)))))), very).
lex(very, (((np(2, 0)->s(21, 0))->np(2, 0)->s(21, 1))-> (np(1, 0)->s(1, 0))->np(0, 0)->s(0, 1)), lambda(A, lambda(B, lambda(C, C+ (appl(B, epsilon)+ (very+appl(appl(A, lambda(D, D)), epsilon)))))), very).
lex(very, (((np(2, 0)->s(21, 0))->np(2, 0)->s(21, 1))-> (np(1, 0)->s(1, 0))->np(1, 0)->s(1, 1)), lambda(A, lambda(B, lambda(C, C+ (appl(B, epsilon)+ (very+appl(appl(A, lambda(D, D)), epsilon)))))), very).
lex(very, (((np(2, 0)->s(21, 0))->np(2, 0)->s(21, 1))-> (np(1, 0)->s(1, 0))->np(21, 0)->s(21, 1)), lambda(A, lambda(B, lambda(C, C+ (appl(B, epsilon)+ (very+appl(appl(A, lambda(D, D)), epsilon)))))), very).
lex(very, (((np(2, 0)->s(21, 0))->np(2, 0)->s(21, 12))-> (np(1, 0)->s(1, 0))->np(0, 0)->s(0, 12)), lambda(A, lambda(B, lambda(C, C+ (appl(B, epsilon)+ (very+appl(appl(A, lambda(D, D)), epsilon)))))), very).
lex(very, (((np(2, 0)->s(21, 0))->np(2, 0)->s(21, 12))-> (np(1, 0)->s(1, 0))->np(1, 0)->s(1, 12)), lambda(A, lambda(B, lambda(C, C+ (appl(B, epsilon)+ (very+appl(appl(A, lambda(D, D)), epsilon)))))), very).
lex(very, (((np(2, 0)->s(21, 0))->np(2, 0)->s(21, 12))-> (np(1, 0)->s(1, 0))->np(21, 0)->s(21, 12)), lambda(A, lambda(B, lambda(C, C+ (appl(B, epsilon)+ (very+appl(appl(A, lambda(D, D)), epsilon)))))), very).

test(1) :-
	parse([captain_jack,served,lobster,yesterday], s(0,0)).
test(2) :-
	parse([captain_jack,served,bananafish,today], s(0,0)).
% fails
test(3) :-
	parse([captain_jack,served,bananafish,very,discreetly], s(0,0)).
% fails
test(4) :-
	parse([captain_jack,served,lobster,yesterday,and,bananafish,today], s(0,0)).
test(5) :-
	parse([lobster,yesterday,end], s(0,0)).
